name: Lint - Markdown

on:
  push:
    paths:
      - "**/*.md"
      - ".markdownlint.jsonc"
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint.jsonc"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: markdownlint
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}":/data \
            markdownlint/markdownlint \
            -c "/data/.markdownlint.jsonc" \
            .
